appName: ghost
image: mukhtarzargar/ghost
port: 3000
imagePullPolicy: Always
replicas: 1

secrets:
  DAPR_APP_PORT: "3500"
  DB_NAME: "ghost"
  JWT_SECRET: "secret"
  MONGO_CONNECTION_URL: "mongodb://root:secretpassword@ghost-mongodb:27017"
  PORT: "3000"
  POST_COLLECTION: "User"
  USER_COLLECTION: "Post"

mongodb:
  enabled: true
  auth:
    enabled: true
    rootUser: root
    rootPassword: "secretpassword"
  service:
    ports:
      mongodb: 27017
