apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ghost-secrets
data:
  DAPR_APP_PORT: {{ .Values.secrets.DAPR_APP_PORT | b64enc | quote }}
  DB_NAME: {{ .Values.secrets.DB_NAME | b64enc | quote }}
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | b64enc | quote }}
  MONGO_CONNECTION_URL: {{ .Values.secrets.MONGO_CONNECTION_URL | b64enc | quote }}
  PORT: {{ .Values.secrets.PORT | b64enc | quote }}
  POST_COLLECTION: {{ .Values.secrets.POST_COLLECTION | b64enc | quote }}
  USER_COLLECTION: {{ .Values.secrets.USER_COLLECTION | b64enc | quote }}
